version: "3"
services:
  drachenlord:
    build: .
    environment:
      DISCORD_API_TOKEN: <PJNgsNW87lADFlAzIZYnEC0Hb28sK0cu>
      ENABLE_RANDOM_JOINS: "True"
      LOGGING_CHANNEL: <your-logging-textchannel-id-as-integer>
